#!/usr/bin/env python3
"""Generate ueventd-perms.sh: apply Android device node ownership (ueventd.rc + init *.rc chown/chmod)
on plain Linux, because modem_control drops to uid system(1000) before opening /dev/modem etc.
usage: gen-ueventd-perms.py vendor/etc/ueventd.rc vendor-init/*.rc > ueventd-perms.sh"""
import sys
AID = {'root': 0, 'system': 1000, 'radio': 1001, 'bluetooth': 1002, 'graphics': 1003, 'input': 1004, 'audio': 1005,
       'camera': 1006, 'log': 1007, 'wifi': 1010, 'media': 1013, 'dhcp': 1014, 'gps': 1021, 'nfc': 1027,
       'audioserver': 1041, 'cameraserver': 1047, 'shell': 2000, 'net_bt_admin': 3001, 'net_bt': 3002,
       'inet': 3003, 'net_raw': 3004}
out = ['#!/bin/sh', '# generated by gen-ueventd-perms.py']
ueventd, rcs = sys.argv[1], sys.argv[2:]
for line in open(ueventd):
    f = line.split('#')[0].split()
    if len(f) >= 4 and f[0].startswith('/dev/') and f[2] in AID and f[3] in AID:
        out.append(f'for n in {f[0]}; do [ -e "$n" ] && chown {AID[f[2]]}:{AID[f[3]]} "$n" && chmod {f[1]} "$n"; done')
for rc in rcs:
    for line in open(rc):
        f = line.split('#')[0].split()
        if len(f) < 3 or f[0] not in ('chown', 'chmod') or not f[-1].startswith(('/dev/', '/sys/', '/proc/')):
            continue
        if f[0] == 'chmod':
            out.append(f'for n in {f[-1]}; do [ -e "$n" ] && chmod {f[1]} "$n"; done')
        elif f[1] in AID and (len(f) == 3 or f[2] in AID):
            g = AID[f[2]] if len(f) == 4 else AID[f[1]]
            out.append(f'for n in {f[-1]}; do [ -e "$n" ] && chown {AID[f[1]]}:{g} "$n"; done')
out.append('# from Android system init.rc: wakelocks are written by uid system')
out.append('for n in /sys/power/wake_lock /sys/power/wake_unlock; do [ -e "$n" ] && chown 1000:1000 "$n" && chmod 0660 "$n"; done')
out.append('true')
print('\n'.join(out))
