#!/bin/sh /etc/rc.common
# Hardware bring-up before netifd: vendor drivers, zram, Wi-Fi (SC2355), first-boot Wi-Fi config, Bluetooth off
START=12
export PATH="$PATH:/opt/mu300/busybox-bin"

boot() {
	/opt/mu300/bin/extra-modules >/tmp/mu300-extra-modules.log 2>&1
	/opt/mu300/bin/zram-start >/dev/null 2>&1
	/opt/mu300/bin/wifi-start >/tmp/mu300-wifi-start.log 2>&1
	/opt/mu300/bin/openwrt-wifi-config >>/tmp/mu300-wifi-start.log 2>&1
}

start() {
	boot
}
